config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "job_postings#index"
  get 'remote', to: "job_postings#remote_only"
  
  namespace :test do
    get 'search', to: "search#search_function"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  validates :title, :company, :salary, presence: true

  def self.search(query) 
    where("lower(title) LIKE :query OR lower(company) LIKE :query 0R salary LIKE :query", query: "%#{query}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  def index 
    @job_postings = JobPosting.all
  end

  def remote_jobs_list
    @remote_jobs = @job_postings.reject { |post| post[:location] != false }
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search_results
    @job_postings = JobPosting.search(params[:query])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/job_postings/index.html.erb
<h1> Job Postings </h1>

<% @job_postings.each do |post| %>
  <h2> Job title: <%= post.title %> </h2>
  <p> Company: <%= post.company %> </p>
  <p> Salary: $<%= post.salary %> </p>
  <p> Location: <%= post.location ? "in-house" : "remote" %> </p>
<% end %>

app/views/job_postings/remote_only.html.erb
<h1> Remote Postings </h1>

<% @remote_jobs.each do |post|%>
  <h2> Job title: <%= post.title %> </h2>
  <p> Company: <%= post.company %> </p>
  <p> Salary: $<%= post.salary %> </p>
  <p> Location: <%= post.location ? "in-house" : "remote" %> </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJobPostings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<%= link_to "See Remote Jobs Only", remote_path %>

<%= form_with url: "/search", method: :get do |form| %>
  <%= form.label :query, "Search openings " %>  
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>